apiVersion: v1
kind: Pod
metadata:
  name: ops-pod-toleration
  namespace: intern-test
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02

  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "ops"
    effect: "NoSchedule"

  containers:
  - name: nginx
    image: nginx
