apiVersion: v1
kind: Pod
metadata:
  name: ops-pod-no-toleration
  namespace: intern-test
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02

  containers:
  - name: nginx
    image: nginx
